apiVersion: v1
kind: Service
metadata:
  labels:
    app: myflaskapp
  name: myflaskapp-svc
  namespace: flaskapp
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32500
  selector:
    app: myflaskapp
  type: NodePort